debug: true

servers:
  - name: "Centrunk"
    type: "FNE2" #FNE2 or CFNE

    ServerPort: 3000
    ServerBindAddress: 0.0.0.0

    RulePath: "./tests/routing_rules.yml"
    ConfigPath: "./tests/router_config.yml"

    # I would love for these to not be needed, but only way to do it right now
    StartCommand: "sudo systemctl start fne2.service"
    StopCommand: "sudo systemctl stop fne2.service"
    RestartCommand: "sudo systemctl restart fne2.service"
    StatusCommand: "sudo systemctl status fne2.service"

  - name: "Centrunk CFNE"
    type: "CFNE" #FNE2 or CFNE

    ServerPort: 3001
    ServerBindAddress: 0.0.0.0

    RulePath: "./tests/cfne_rules.yml"
    ConfigPath: "./tests/cfne_rules.yml"

    # I would love for these to not be needed, but only way to do it right now
    StartCommand: "sudo systemctl start cfne.service"
    StopCommand: "sudo systemctl stop cfne.service"
    RestartCommand: "sudo systemctl restart cfne.service"
    StatusCommand: "sudo systemctl status cfne.service"