Debug: false
LogPath: "./logs/tg_manager.log" # If you do not want to log to a file, comment this line

Servers:
  - name: "Centrunk"
    type: "CFNE" # FNE2 or CFNE

    AutoAclInterval: 60 # 0 to disable. Time in minutes

    ServerPort: 3001
    ServerBindAddress: 0.0.0.0

    Rest:
      address: "127.0.0.1"
      port: 9990
      password: "passw0rd"

    PeerWatcher:
      enabled: false
      interval: 5 # Time in minutes

    Mailer:
      enabled: false
      fromEmail: "test@example.com"
      SocketLabs:
        enabled: false
        serverId: "123456"
        injectionApi: "xxxxxxxxxxxxxxxxxx"

    Sheets:
      enabled: false
      autoUpdateFne: false
      sheetId: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      serviceAccountKeyFile: "configs/google.json"
      RidAcl:
        tab: "RID_ACL"
        range: "A:B"

    Twilio:
      enabled: false
      fromNumber: "+1234567890"
      serverPort: 3601 # For inbound sms
      inbound: false
      outboundCall: false
      outboundSms: false # Not implemented
      accountSid: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      authToken: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

    Discord:
      enabled: false
      token: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      clientId: "00000000000000000"
      guildId: "111111111111111111"
      channelNameStats:
        enabled: false
        affiliationChannelId: "0000000000000000"
        affiliationInterval: 1
        peerChannelId: "0000000000000000000000"
        peerInterval: 2
      Webhook:
        enabled: false
        url: "https://discord.com/" # Not used in PeerWatcher

    Telegram:
      enabled: false
      token: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

    RulePath: "./tests/cfne_rules.yml"
    ConfigPath: "./tests/cfne_rules.yml"

    # I would love for these to not be needed, but only way to do it right now
    StartCommand: "sudo systemctl start cfne.service"
    StopCommand: "sudo systemctl stop cfne.service"
    RestartCommand: "sudo systemctl restart cfne.service"
    StatusCommand: "sudo systemctl status cfne.service"

  - name: "Some FNE2" # FNE2 is no longer support, but some features will work
    type: "FNE2" # FNE2 or CFNE

    ServerPort: 3000
    ServerBindAddress: 0.0.0.0

    RulePath: "./tests/routing_rules.yml"
    ConfigPath: "./tests/router_config.yml"

    # I would love for these to not be needed, but only way to do it right now
    StartCommand: "sudo systemctl start fne2.service"
    StopCommand: "sudo systemctl stop fne2.service"
    RestartCommand: "sudo systemctl restart fne2.service"
    StatusCommand: "sudo systemctl status fne2.service"